# src/clustering/run_multi_clustering.py
import logging
from pathlib import Path
import pandas as pd
from typing import Any

from src.clustering.cluster_snapshots import (
    run_kmeans,
    run_gmm,
    save_clustering_outputs
)
from src.clustering.cluster_analysis import (
    cluster_size_summary,
    top_features_per_cluster,
    representative_samples,
    save_cluster_analysis_tables
)

LOGGER = logging.getLogger(__name__)

def run_and_save_algorithm(
    df: pd.DataFrame, 
    config: dict[str, Any], 
    method: str, 
    output_dir: Path
):
    LOGGER.info(f"Running {method.upper()} clustering...")
    if method == "kmeans":
        result = run_kmeans(df, config)
    elif method == "gmm":
        result = run_gmm(df, config)
    else:
        raise ValueError(f"Method {method} not supported in multi_clustering")

    # Save base clustering outputs
    save_clustering_outputs(result, output_dir)
    
    # Generate and save analysis tables
    clustered_df = result["clustered_df"]
    centroids_df = result["centroids_df"]
    feature_cols = result["feature_cols"]
    
    size_df = cluster_size_summary(clustered_df)
    top_features_df = top_features_per_cluster(centroids_df)
    samples_df = representative_samples(clustered_df, centroids_df, feature_cols)
    
    save_cluster_analysis_tables(size_df, top_features_df, samples_df, output_dir)
    
    # Generate basic cluster labels if missing so GUI loads smoothly
    labels_path = output_dir / "cluster_labels.csv"
    if not labels_path.exists():
        labels_df = pd.DataFrame([
            {
                "cluster_id": c, 
                "label": f"{method.upper()} Cluster {c}", 
                "description": f"Auto-generated by {method.upper()}"
            } 
            for c in size_df["cluster_label"]
        ])
        labels_df.to_csv(labels_path, index=False)
        
    LOGGER.info(f"Saved {method.upper()} outputs to {output_dir}")
